-- public.service definition

-- Drop table

-- DROP TABLE public.service;

CREATE TABLE public.service (
	service_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	active bool NULL,
	created_at timestamp(6) NULL,
	description varchar(255) NULL,
	service_name varchar(255) NOT NULL,
	updated_at timestamp(6) NULL,
	CONSTRAINT service_pkey PRIMARY KEY (service_id)
);


-- public.application_user definition

-- Drop table

-- DROP TABLE public.application_user;

CREATE TABLE public.application_user (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	account_non_expired bool NULL,
	account_non_locked bool NULL,
	created_at timestamp(6) NULL,
	credentials_non_expired bool NULL,
	enabled bool NULL,
	"password" varchar(255) NOT NULL,
	roles varchar(255) NULL,
	updated_at timestamp(6) NULL,
	username varchar(255) NOT NULL,
	customer_customer_id int8 NULL,
	provider_provider_id int8 NULL,
	user_info_user_info_id int8 NULL,
	CONSTRAINT application_user_pkey PRIMARY KEY (id),
	CONSTRAINT uk4p53bq0ny4k57ewdifljvebl9 UNIQUE (customer_customer_id),
	CONSTRAINT uk6c0v0rco93sykgyetukfmkkod UNIQUE (username),
	CONSTRAINT uk7mu0cjaei0x2sagj04sxpmu2p UNIQUE (provider_provider_id),
	CONSTRAINT ukrxlqq36as3sedt6f28t0rrmfg UNIQUE (user_info_user_info_id)
);


-- public.booking definition

-- Drop table

-- DROP TABLE public.booking;

CREATE TABLE public.booking (
	booking_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamp(6) NULL,
	remarks varchar(255) NULL,
	status varchar(255) NOT NULL,
	updated_at timestamp(6) NULL,
	customer_id int8 NOT NULL,
	service_id int8 NOT NULL,
	CONSTRAINT booking_pkey PRIMARY KEY (booking_id),
	CONSTRAINT booking_status_check CHECK (((status)::text = ANY ((ARRAY['BOOKED'::character varying, 'CANCELLED'::character varying, 'PENDING'::character varying, 'COMPLETED'::character varying])::text[])))
);


-- public.customer definition

-- Drop table

-- DROP TABLE public.customer;

CREATE TABLE public.customer (
	customer_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamp(6) NULL,
	status varchar(255) NULL,
	updated_at timestamp(6) NULL,
	user_id int8 NOT NULL,
	user_status varchar(255) NULL,
	CONSTRAINT customer_pkey PRIMARY KEY (customer_id),
	CONSTRAINT customer_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying, 'SUSPENDED'::character varying])::text[]))),
	CONSTRAINT customer_user_status_check CHECK (((user_status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying, 'SUSPENDED'::character varying])::text[]))),
	CONSTRAINT ukj7ja2xvrxudhvssosd4nu1o92 UNIQUE (user_id)
);


-- public.provider definition

-- Drop table

-- DROP TABLE public.provider;

CREATE TABLE public.provider (
	provider_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	about_me varchar(255) NULL,
	created_at timestamp(6) NULL,
	status varchar(255) NULL,
	updated_at timestamp(6) NULL,
	user_id int8 NOT NULL,
	user_status varchar(255) NULL,
	CONSTRAINT provider_pkey PRIMARY KEY (provider_id),
	CONSTRAINT provider_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying, 'SUSPENDED'::character varying])::text[]))),
	CONSTRAINT provider_user_status_check CHECK (((user_status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying, 'SUSPENDED'::character varying])::text[]))),
	CONSTRAINT uk8oc1o2uw5cl4vnitihnb5dfi5 UNIQUE (user_id)
);


-- public.provider_service definition

-- Drop table

-- DROP TABLE public.provider_service;

CREATE TABLE public.provider_service (
	deleted bool NULL,
	provider_id int8 NOT NULL,
	service_id int8 NOT NULL,
	CONSTRAINT provider_service_pkey PRIMARY KEY (provider_id, service_id)
);


-- public.slot definition

-- Drop table

-- DROP TABLE public.slot;

CREATE TABLE public.slot (
	slot_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamp(6) NULL,
	"date" date NOT NULL,
	end_time time(0) NOT NULL,
	start_time time(0) NOT NULL,
	status varchar(255) NOT NULL,
	updated_at timestamp(6) NULL,
	booking_id int8 NULL,
	provider_id int8 NOT NULL,
	CONSTRAINT slot_pkey PRIMARY KEY (slot_id),
	CONSTRAINT slot_status_check CHECK (((status)::text = ANY ((ARRAY['AVAILABLE'::character varying, 'BOOKED'::character varying, 'BLOCKED'::character varying])::text[])))
);


-- public.user_info definition

-- Drop table

-- DROP TABLE public.user_info;

CREATE TABLE public.user_info (
	user_info_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	address varchar(255) NULL,
	city varchar(50) NOT NULL,
	created_at timestamp(6) NULL,
	email varchar(255) NULL,
	firstname varchar(50) NOT NULL,
	lastname varchar(50) NULL,
	phone varchar(20) NOT NULL,
	profile_pic oid NULL,
	updated_at timestamp(6) NULL,
	user_id int8 NULL,
	CONSTRAINT ukhixwjgx0ynne0cq4tqvoawoda UNIQUE (user_id),
	CONSTRAINT user_info_pkey PRIMARY KEY (user_info_id)
);


-- public.application_user foreign keys

ALTER TABLE public.application_user ADD CONSTRAINT fk7nqxgo5l3llce1se4raot2ho5 FOREIGN KEY (customer_customer_id) REFERENCES public.customer(customer_id);
ALTER TABLE public.application_user ADD CONSTRAINT fkaqiklbafo0536hmhfmx5eyvir FOREIGN KEY (provider_provider_id) REFERENCES public.provider(provider_id);
ALTER TABLE public.application_user ADD CONSTRAINT fkn19kivuxn2uj64aqnejifrpq8 FOREIGN KEY (user_info_user_info_id) REFERENCES public.user_info(user_info_id);


-- public.booking foreign keys

ALTER TABLE public.booking ADD CONSTRAINT fkcebnlefwi9r13txu8btclnmsu FOREIGN KEY (service_id) REFERENCES public.service(service_id);
ALTER TABLE public.booking ADD CONSTRAINT fklnnelfsha11xmo2ndjq66fvro FOREIGN KEY (customer_id) REFERENCES public.customer(customer_id);


-- public.customer foreign keys

ALTER TABLE public.customer ADD CONSTRAINT fkm02uwh0r19ldmel2lgtkjc4g7 FOREIGN KEY (user_id) REFERENCES public.application_user(id);


-- public.provider foreign keys

ALTER TABLE public.provider ADD CONSTRAINT fkjyyue89qe7ma7uwmspl3x188c FOREIGN KEY (user_id) REFERENCES public.application_user(id);


-- public.provider_service foreign keys

ALTER TABLE public.provider_service ADD CONSTRAINT fk1yn1847eqx9bf7bwg5p0iyed0 FOREIGN KEY (provider_id) REFERENCES public.provider(provider_id);
ALTER TABLE public.provider_service ADD CONSTRAINT fk30qsy77u16i3iic1lpqfk67xm FOREIGN KEY (service_id) REFERENCES public.service(service_id);


-- public.slot foreign keys

ALTER TABLE public.slot ADD CONSTRAINT fkeuogmex50jynonjdfux9kcahf FOREIGN KEY (booking_id) REFERENCES public.booking(booking_id);
ALTER TABLE public.slot ADD CONSTRAINT fkt9px1eehdneajqm3ont33wo89 FOREIGN KEY (provider_id) REFERENCES public.provider(provider_id);


-- public.user_info foreign keys

ALTER TABLE public.user_info ADD CONSTRAINT fk9cx15rudn7lqoog7guvmptjp2 FOREIGN KEY (user_id) REFERENCES public.application_user(id);